# -Path: "PokeRotom/docker-compose.yml"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: pokerotom-client
        ports:
            - '5173:5173'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - VITE_API_URL=http://127.0.0.1:3000
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - server
        restart: always

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: pokerotom-server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '3000:3000'
        env_file:
            - ./server/.env
        environment:
            - SERVER_HOSE=0.0.0.0
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=production
        command: pnpm start:dev
        restart: always

    mongodb:
        image: mongo:latest
        container_name: pokerotom-mongodb
        ports:
            - '27017:27017'
        volumes:
            - pokerotom_data:/data/db
        restart: always

volumes:
    pokerotom_data:
